// <auto-generated />
namespace Vcpmc.Mis.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IsConvertSign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsConvertSign));
        
        string IMigrationMetadata.Id
        {
            get { return "202007070422180_IsConvertSign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
