//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcpmc.Mis.AppMatching.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vcpmc.Mis.AppMatching.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of task.
        /// </summary>
        internal static string Beginning_of_task {
            get {
                return ResourceManager.GetString("Beginning_of_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check output in directory.
        /// </summary>
        internal static string Check_output_in_directory {
            get {
                return ResourceManager.GetString("Check_output_in_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion completed..
        /// </summary>
        internal static string Conversion_completed {
            get {
                return ResourceManager.GetString("Conversion_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Status.
        /// </summary>
        internal static string Conversion_Status {
            get {
                return ResourceManager.GetString("Conversion_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert from .
        /// </summary>
        internal static string Convert_from_ {
            get {
                return ResourceManager.GetString("Convert_from_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        internal static string Converting {
            get {
                return ResourceManager.GetString("Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of task.
        /// </summary>
        internal static string End_of_task {
            get {
                return ResourceManager.GetString("End_of_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire directory, including sub.
        /// </summary>
        internal static string Entire_directory_including_sub {
            get {
                return ResourceManager.GetString("Entire_directory_including_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string File_does_not_exist {
            get {
                return ResourceManager.GetString("File_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interface.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutOfMemoryError.
        /// </summary>
        internal static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Source Encoding option..
        /// </summary>
        internal static string Select_a_Source_Encoding_option {
            get {
                return ResourceManager.GetString("Select_a_Source_Encoding_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Directory.
        /// </summary>
        internal static string Select_Directory {
            get {
                return ResourceManager.GetString("Select_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select Files.
        /// </summary>
        internal static string Select_Files {
            get {
                return ResourceManager.GetString("Select_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Encoding.
        /// </summary>
        internal static string Source_Encoding {
            get {
                return ResourceManager.GetString("Source_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vietnamese.
        /// </summary>
        internal static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
